# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 622220948a65f202bd2b43fcdd8a7e2c7a18143faad65407481f855eaf81b52910bc0a1cadcb36daabc3696c589390a3f3826a4fd019cdc063eba77de324263d

test:
  secret_key_base: 000e26a4e5bf29a070099108fbfe3161ba2886fa64cae990188bdb09040b824828f87cb6d997b9f01e78b47521c6b36a535d8000a95b3c4e4a51060761b54291

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
